# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-20 20:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('washeryapp', '0003_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='piece_count',
            field=models.IntegerField(default=0),
        ),
    ]
