# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-24 02:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('washeryapp', '0004_item_piece_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cleaner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='washeryapp.Cleaner')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='washeryapp.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='washeryapp.Driver')),
            ],
        ),
        migrations.CreateModel(
            name='Stop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=500)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='washeryapp.Customer')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='washeryapp.Invoice')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='washeryapp.Route')),
            ],
        ),
    ]
