# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-24 04:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('washeryapp', '0005_invoice_route_stop'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='address',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='invoice',
            name='status',
            field=models.IntegerField(choices=[(1, 'Cleaning'), (2, 'Ready'), (3, 'On the way'), (4, 'Delivered')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice',
            name='total',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
