# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-01 18:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('washeryapp', '0009_auto_20170901_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='ready_by',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
