# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-01 21:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('washeryapp', '0012_auto_20170901_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waypoint',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='washeryapp.Customer'),
        ),
        migrations.AlterField(
            model_name='waypoint',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='washeryapp.Invoice'),
        ),
    ]
