# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-01 21:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('washeryapp', '0013_auto_20170901_2100'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
