# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-01 21:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('washeryapp', '0014_route_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='waypoint',
            name='waypoint_type',
            field=models.IntegerField(choices=[(1, 'Pick up'), (2, 'Drop off')], default=1),
            preserve_default=False,
        ),
    ]
