# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-02 20:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('washeryapp', '0015_waypoint_waypoint_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor', models.IntegerField(choices=[(1, 'Stripe'), (2, 'Paypal')])),
                ('token', models.CharField(max_length=500)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='washeryapp.Customer')),
            ],
        ),
        migrations.RemoveField(
            model_name='waypoint',
            name='customer',
        ),
        migrations.AddField(
            model_name='invoice',
            name='dropoff_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice',
            name='dropoff_period',
            field=models.IntegerField(choices=[(100, 'Morning'), (101, 'Evening')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice',
            name='pickup_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice',
            name='pickup_period',
            field=models.IntegerField(choices=[(100, 'Morning'), (101, 'Evening')], default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.IntegerField(choices=[(6, 'REQUESTED'), (5, 'Picked Up'), (1, 'Cleaning'), (2, 'Ready'), (3, 'On the way'), (4, 'Delivered')]),
        ),
        migrations.AlterField(
            model_name='waypoint',
            name='invoice',
            field=models.ForeignKey(default=21, on_delete=django.db.models.deletion.CASCADE, to='washeryapp.Invoice'),
            preserve_default=False,
        ),
    ]
