# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-02 20:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('washeryapp', '0016_auto_20170902_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.IntegerField(choices=[(6, 'Requested'), (5, 'Picked Up'), (1, 'Cleaning'), (2, 'Ready'), (3, 'On the way'), (4, 'Delivered')]),
        ),
    ]
