# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-09 16:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('washeryapp', '0018_auto_20170903_0140'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='paid_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
