# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-01 20:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('washeryapp', '0019_invoice_paid_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='cleaner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='washeryapp.Cleaner'),
            preserve_default=False,
        ),
    ]
