# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-02 03:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('washeryapp', '0022_auto_20171001_2351'),
    ]

    operations = [
        migrations.AddField(
            model_name='waypoint',
            name='latitude',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='waypoint',
            name='longitude',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=9),
            preserve_default=False,
        ),
    ]
