# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-04 17:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('washeryapp', '0024_auto_20171002_0344'),
    ]

    operations = [
        migrations.AddField(
            model_name='waypoint',
            name='waypoint_order',
            field=models.IntegerField(default=0),
        ),
    ]
